apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: odooctl-previews
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/example/acme-odoo.git
        revision: gitops-previews
        directories:
          - path: deploy/gitops/previews/*
  template:
    metadata:
      name: '{{.path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: odoo-previews
      source:
        repoURL: https://github.com/example/acme-odoo.git
        targetRevision: gitops-previews
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
